name: 'Simple Github Release'
description: 'Create a Github release'
branding:
  icon: upload
  color: green
inputs:
  major-version:
    description: 'Major version number for the release tag'
    required: true
    default: '0'
  minor-version:
    description: 'Minor version number for the release tag'
    required: true
    default: '0'
  patch-version:
    description: 'Patch version number for the release tag - if omitted, will use previous tag patch version + 1'
    required: false
  num_releases_to_keep:
    description: 'Number of Github releases to keep - will prune the oldest releases up to the number specified. By default will keep all releases'
    required: false
  tag_major_version:
    description: 'If true, will update the major version tag (e.g. v2) to point to the newest published release (e.g. v2.1.4)'
    required: false
runs:
  using: 'node20'
  main: 'index.js'
