name: 'Simple Github Release'
description: 'Create a Github release'
branding:
  icon: upload
  color: green
inputs:
  major-version:
    description: 'Major version number for the release tag'
    required: true
    default: '0'
  minor-version:
    description: 'Minor version number for the release tag'
    required: true
    default: '0'
  patch-version:
    description: 'Patch version number for the release tag - if omitted, will use previous tag patch version + 1'
    required: false
  num_releases_to_keep:
    description: 'Number of Github releases to keep - will prune the oldest releases up to the number specified. By default will keep all releases'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    MAJOR_VERSION: ${{ inputs.major-version }}
    MINOR_VERSION: ${{ inputs.minor-version }}
    PATCH_VERSION: ${{ inputs.patch-version }}
    NUM_RELEASES_TO_KEEP: ${{ inputs.num_releases_to_keep }}
